name: Deploy latest repo code as mlproject on databricks

on:
  push:
    branches:
      - never_run
jobs:
  training:
#    if: github.actor == 'sshruti23'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Create a new cluster for databricks job to run
        id: cluster_id
        run: |
            <call script here cluster_creation.sh>
      - name: Update pipeline request body json with cluster id
        run: |
            python github_workflows/create_request_body "${{ env.cluster_id }}"
      - name: Create And Start A Databricks Job For Training Model
        run: |
            <call script here training_job.sh>
  register:
    if: github.actor == 'sshruti23'
    runs-on: ubuntu-latest
    needs: training
    environment: 'register'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Echo Something
        run: |
              echo "I'm a echo from prod stage"
