experiment:
  name: "sklearn_regression_experiment_4"
  tracking_uri: "http://localhost:9000"
  artifact_location: "./artifacts"

model_registry:
  registry_uri: "./registry"
  model_name: "taxi_fare_regressor_4"

SPLIT_RATIOS: [ 0.80, 0.10, 0.10 ]

INGEST_CONFIG:
  using: parquet
  location: "./request_body/sample.parquet"

INGEST_SCORING_CONFIG:
  using: parquet
  location: "./request_body/sample.parquet"

PREDICT_OUTPUT_CONFIG:
  using: parquet
  location: "./request_body/sample_output.parquet"
