name: Deploy latest repo code as mlproject on databricks

on: [push]

jobs:
  training:
#    if: github.actor == 'sshruti23'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name : Check Files In Current Directory
        run : |
              ls -la
      - name: Submit A Databricks Job For Training model
        run: |
             curl -X POST https://dbc-024af671-5f60.cloud.databricks.com/api/2.1/jobs/runs/submit \
              -H "Authorization:Bearer ${{ secrets.AWS_DB_TOKEN }}" \
              -H "Content-Type: application/json" \
              --data @pipeline_request_body/training.json
  register:
    if: github.actor == 'sshruti23'
    runs-on: ubuntu-latest
    needs: training
    environment: 'register'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name : Echo Something
        run : |
              echo "I'm a echo from prod stage"