name: Deploy latest repo code as mlproject on databricks

on: [push]

jobs:
  training:
#    if: github.actor == 'sshruti23'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name : Install Dependencies
        run : |
            python --version 
            pip install databricks-cli
      - name : Create a new cluster for databricks job to run
        id: cluster_id
        run : |
          output=$(curl -X POST https://${{ secrets.AWS_DB_HOST }}/api/2.0/clusters/create \
                        -H "Authorization:Bearer ${{ secrets.AWS_DB_TOKEN }}" \
                        -H "Content-Type: application/json" \
                        --data @pipeline_request_body/cluster_creation_request.json)
          id=$( jq -r  '.cluster_id' <<< "${output}" )
          echo "cluster_id=$id" >> $GITHUB_ENV
      - name: Echo the cluster value
        run: |
          echo "I'm echo printing cluster id value"
          echo "${{ env.cluster_id }}"
      - name: Submit A Databricks Job For Training model
        run: |
             curl -X POST https://${{ secrets.AWS_DB_HOST }}/api/2.1/jobs/runs/submit \
              -H "Authorization:Bearer ${{ secrets.AWS_DB_TOKEN }}" \
              -H "Content-Type: application/json" \
              --data @pipeline_request_body/training_single_cluster.json
  register:
    if: github.actor == 'sshruti23'
    runs-on: ubuntu-latest
    needs: training
    environment: 'register'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name : Echo Something
        run : |
              echo "I'm a echo from prod stage"