name: Deploy latest repo code as mlproject on databricks
on: [push]
jobs:
  training:
    if: github.actor == 'sshruti23'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Create A Databricks Job For Training Model
        id: job_id
        run: |
          output=$(curl -X POST https://${{ secrets.AWS_DB_HOST }}/api/2.1/jobs/create \
            -H "Authorization:Bearer ${{ secrets.AWS_DB_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data @github_workflows/data/training_job.json)
           id=$( jq -r  '.job_id' <<< "${output}" )
           echo "job_id=$id" >> $GITHUB_ENV
      - name: Echo Job Id
        run: |
           echo "${{ env.job_id }}"
      - name: Run the Databrick Workflow Job
        run: |          
          curl -X POST https://${{ secrets.AWS_DB_HOST }}/api/2.1/jobs/run-now \
            -H "Authorization:Bearer ${{ secrets.AWS_DB_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data '{"job_id": "${{ env.job_id }}" }'
  register:
    if: github.actor == 'sshruti23'
    runs-on: ubuntu-latest
    needs: training
    environment: 'register'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Echo Something
        run: |
              echo "I'm a echo from register stage"